### ISSUE TITLE
(dracula) JetBrains Original vs Dracula Theme

### ISSUE THREAD

**Issue by RobLoach** [tinted-theming/schemes#20]
The [Dracula Scheme](https://github.com/tinted-theming/schemes/blob/spec-0.11/base24/dracula.yaml) has colors that are aligned with the super old JetBrains theme. Since then, there's been a launch of [DraculaTheme.com](https://draculatheme.com/contribute) , which has a similar, but different, color set.

![Screenshot from 2024-07-17 12-26-42](https://github.com/user-attachments/assets/6a16699a-ddea-4f71-8067-667a9498e286)

I'd like to propose updating the provided Dracula Scheme to match this newer palette. While it is preference, I do prefer this new one over the old one.

RE: @fredHappyface

**Comment by JamyGolden** [comment]
Updated with new colours, more information in the above closed PR.
