### ISSUE TITLE
Scheme color viewer / comparison

### ISSUE THREAD

**Issue by nico-i** [tinted-theming/schemes#22]
I wanted to be able to quickly view the colors of the schemes present in this repo so I created a [simple little static page](https://nico-i.github.io/scheme-viewer) for anyone else who preferes a more visual comparison.

 Repo: https://github.com/nico-i/scheme-viewer

**Comment by JamyGolden** [comment]
That's great! We have a gallery for base16, but it's only linked to on https://github.com/tinted-theming/home, not on the schemes repo, so I've created a PR add a link to the gallery on this repo and I've also included a link to your base24 gallery in the readme. I'll merge the PR when you give it a thumbs up :smile:

**Comment by nico-i** [comment]
Oh, I didn't see the link in the original repo :D
But I'm still glad I made some sort of contribution, haha

**Comment by JamyGolden** [comment]
Yeah I still think it's useful for base16 too, Some people might not want to see the syntax highlighting and just see the scheme colors and yours does that well!
